# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='img_url',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='sneaker_images'),
        ),
    ]
